// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// length_cpp
int length_cpp(NumericVector x);
RcppExport SEXP _BIOSTAT625ttest_length_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(length_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// mean_cpp
float mean_cpp(NumericVector x);
RcppExport SEXP _BIOSTAT625ttest_mean_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(mean_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// sd_cpp
float sd_cpp(NumericVector x);
RcppExport SEXP _BIOSTAT625ttest_sd_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(sd_cpp(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BIOSTAT625ttest_length_cpp", (DL_FUNC) &_BIOSTAT625ttest_length_cpp, 1},
    {"_BIOSTAT625ttest_mean_cpp", (DL_FUNC) &_BIOSTAT625ttest_mean_cpp, 1},
    {"_BIOSTAT625ttest_sd_cpp", (DL_FUNC) &_BIOSTAT625ttest_sd_cpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_BIOSTAT625ttest(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
