# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Finds the length of a vector (or array)
#'
#' @param x Numeric vector in R
length_cpp <- function(x) {
    .Call(`_BIOSTAT625ttest_length_cpp`, x)
}

#' Finds the mean of a vector
#'
#' @param x Numeric vector in R
mean_cpp <- function(x) {
    .Call(`_BIOSTAT625ttest_mean_cpp`, x)
}

#' Finds the standard deviation of a vector (or array)
#'
#' @param x Numeric vector in R
sd_cpp <- function(x) {
    .Call(`_BIOSTAT625ttest_sd_cpp`, x)
}

